config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :static_pages, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		@user_name = params[:user_name]
		if @user_name
			begin
				@user_id = flickr.people.findByUsername(username: @user_name)
				@list = flickr.people.getPhotos(user_id: @user_id.id)
			rescue
				@error = "Invalid User Name!" if @list.nil?
			end
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosait</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Search a Flickr User</h1>

<%= form_tag(static_pages_path, method: "get") do %>
	<%= label_tag(:user_name, "User Name") %>
	<%= text_field_tag(:user_name) %><br><br>

	<%= submit_tag("Search") %><br><br>
<% end %>

<% if @user_name && @error.nil? %>
	<% @list.each do |photo| %>
		<%= image_tag(FlickRaw.url_z(photo), :size => "400x250") %>
	<% end %>
<% else %>
	<h2><%= @error %></h2>
<% end %>